### ISSUE TITLE
No named parameter with the name 'swapAnimationDuration'

### ISSUE THREAD

**Issue by Toliambus** [Faiz-rhm/Flutter-Crypto-App#3]
Do you know how to fix the issue?

lib/widget/asset_card.dart:101:19: Error: No named parameter with the name 'swapAnimationDuration'.
                  swapAnimationDuration: const Duration(milliseconds: 150),
                  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Tolik/AppData/Local/Pub/Cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/line_chart/line_chart.dart:14:9: Context: Found this candidate, but the arguments don't match.
  const LineChart(
        ^^^^^^^^^
lib/screen/static_page.dart:120:17: Error: No named parameter with the name 'swapAnimationDuration'.
                swapAnimationDuration: const Duration(milliseconds: 150),
                ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Tolik/AppData/Local/Pub/Cache/hosted/pub.dev/fl_chart-0.65.0/lib/src/chart/line_chart/line_chart.dart:14:9: Context: Found this candidate, but the arguments don't match.
  const LineChart(
        ^^^^^^^^^
Failed to compile application.

**Comment by Faiz-rhm** [comment]
fixed
